### ISSUE TITLE
ubuntu20出现No module named 'distro'

### ISSUE THREAD

**Issue by WinCherry** [fishros/install#24]
进行wget http://fishros.com/install -O fishros && . fishros命令输入时
出现了以下报错：
WARN:No Yaml Module!
Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 90, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 30, in main
    from tools.base import CmdTask,FileUtils,PrintUtils,ChooseTask
  File "/tmp/fishinstall/tools/base.py", line 775, in <module>
    osversion = GetOsVersion()
  File "/tmp/fishinstall/tools/base.py", line 105, in GetOsVersion
    import distro
ModuleNotFoundError: No module named 'distro'
然后进行了 pip install pyyaml和 pip install distro，完成安装后依旧报这个错误无法运行

**Comment by WinCherry** [comment]
系统中存在Python2.7、python3.8、python3.9，pip默认使用python3.9

**Comment by WinCherry** [comment]
请问能帮忙解决一下吗，感激（O^O)
