### ISSUE TITLE
Unavailable on macOS Sonoma

### ISSUE THREAD

**Issue by HuaYuXiao** [fishros/install#42]
```
(base) hyx020222@MacBook-Pro-4 ~ % wget http://fishros.com/install -O fishros && . fishros
--2023-12-05 09:08:12--  http://fishros.com/install
Resolving fishros.com (fishros.com)... 139.9.131.171
Connecting to fishros.com (fishros.com)|139.9.131.171|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://fishros.com/install/ [following]
--2023-12-05 09:08:13--  http://fishros.com/install/
Reusing existing connection to fishros.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 582 [application/octet-stream]
Saving to: ‘fishros’

fishros                                            100%[================================================================================================================>]     582  --.-KB/s    in 0s      

2023-12-05 09:08:13 (69.4 MB/s) - ‘fishros’ saved [582/582]

.: no such file or directory: fishros
```

**Comment by HuaYuXiao** [comment]
According to https://github.com/fishros/install/issues/22#issuecomment-1446536778, after I replaced `.  fishros` with `bash fishros`,

```
(base) hyx020222@MacBook-Pro-4 ~ % wget http://fishros.com/install -O fishros && bash fishros
--2023-12-05 09:12:09--  http://fishros.com/install
Resolving fishros.com (fishros.com)... 139.9.131.171
Connecting to fishros.com (fishros.com)|139.9.131.171|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://fishros.com/install/ [following]
--2023-12-05 09:12:09--  http://fishros.com/install/
Reusing existing connection to fishros.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 582 [application/octet-stream]
Saving to: ‘fishros’

fishros                                            100%[================================================================================================================>]     582  --.-KB/s    in 0s      

2023-12-05 09:12:09 (29.2 MB/s) - ‘fishros’ saved [582/582]

Password:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

--2023-12-05 09:12:13--  http://fishros.com/install/install1s/tools/base.py
Resolving fishros.com (fishros.com)... 139.9.131.171
Connecting to fishros.com (fishros.com)|139.9.131.171|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44694 (44K) [application/octet-stream]
Saving to: ‘/tmp/fishinstall/tools/base.py’

/tmp/fishinstall/tools/base.py                     100%[================================================================================================================>]  43.65K  --.-KB/s    in 0.1s    

2023-12-05 09:12:13 (398 KB/s) - ‘/tmp/fishinstall/tools/base.py’ saved [44694/44694]

WARN:No Yaml Module!
Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 122, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 57, in main
    from tools.base import CmdTask,FileUtils,PrintUtils,ChooseTask,ChooseWithCategoriesTask
  File "/private/tmp/fishinstall/tools/base.py", line 775, in <module>
    osversion = GetOsVersion()
  File "/private/tmp/fishinstall/tools/base.py", line 105, in GetOsVersion
    import distro
ModuleNotFoundError: No module named 'distro'
fishros: line 16: /Users/hyx020222/.bashrc: No such file or directory
```

**Comment by ganyuanzhen** [comment]
此问题是由于，macOS并没有ROS2的二进制发行版本，因此，我们无法编写一个一键安装程序在macOS上使用。

但是，由于macOS支持docker，因此，可以尝试使用docker安装。

目前的安装程序仅在Ubuntu上可以使用

**Comment by HuaYuXiao** [comment]
谢谢，我已经解决了这个问题。祝好—————————————华羽霄系统设计与智能制造学院南方科技大学深圳 ***@***.***+86-13701490089On Dec 7, 2023, at 16:46, Yinan Qin ***@***.***> wrote:﻿
此问题是由于，macOS并没有ROS2的二进制发行版本，因此，我们无法编写一个一键安装程序在macOS上使用。
但是，由于macOS支持docker，因此，可以尝试使用docker安装。
目前的安装程序仅在Ubuntu上可以使用
