### ISSUE TITLE
Ubuntu 20.04 下一键安装提示 “AttributeError: module 'tools.tool_install_ros' has no attribute 'Tool'”

### ISSUE THREAD

**Issue by andiven** [fishros/install#46]
````
/tmp/fishinstall/to 100%[===================>]   7.53K  --.-KB/s    in 0s      

2024-01-22 15:03:36 (470 MB/s) - ‘/tmp/fishinstall/tools/tool_config_system_source.py’ saved [7708/7708]

Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 122, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 114, in main
    run_tool_file(tools[code]['tool'].replace(url_prefix,'').replace("/","."))
  File "/tmp/fishinstall/tools/base.py", line 1295, in run_tool_file
    tool = importlib.import_module(file.replace(".py","")).Tool()
AttributeError: module 'tools.tool_install_ros' has no attribute 'Tool'
```

**Comment by ganyuanzhen** [comment]
在这边没能复现错误，可以看看网络是否正常等等

**Comment by fishros** [comment]
多半网络问题，重试几次
