### ISSUE TITLE
Ubuntu20.04 运行一键安装出现问题：

### ISSUE THREAD

**Issue by t1tqq** [fishros/install#53]
WARN:No Yaml Module!
Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 123, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 58, in main
    from tools.base import CmdTask,FileUtils,PrintUtils,ChooseTask,ChooseWithCategoriesTask
  File "/tmp/fishinstall/tools/base.py", line 773, in <module>
    osversion = GetOsVersion()
  File "/tmp/fishinstall/tools/base.py", line 103, in GetOsVersion
    import distro
ModuleNotFoundError: No module named 'distro'
已经用了pip3 install distro后依然没有解决
请问这个是什么问题？

**Comment by fishros** [comment]
需要使用 sudo pip3 install distro 试一试或者 sudo apt install python3-distro

**Comment by wuyukun-tong** [comment]
我也遇到的相同的问题，sudo pip3 install distro 运行这个命令之后好了
